import type { DomainPack } from '../../shared/domainPackTypes';

export const genomicMedicinePack: DomainPack = {
  id: 'genomic-medicine',
  label: 'Genomic Medicine',
  tagline: 'Consent-aware genomic research graphs',
  description:
    'A bundled domain pack for modelling de-identified genomic research as linked Holons: cohorts, consent, samples, sequencing data, phenotypes, pipeline runs, evidence, and review.',
  status: 'bundled',
  docsPath: 'OASIS-IDE/docs/holonic_genomic_medicine_proposal.md',
  holonSchemas: [
    {
      id: 'research-program',
      name: 'ResearchProgramHolon',
      category: 'Governance',
      description: 'Umbrella program for scope, sponsor, policy, and linked studies.',
      fields: ['programId', 'title', 'sponsor', 'scope', 'dataSensitivity', 'status']
    },
    {
      id: 'irb-protocol',
      name: 'IRBProtocolHolon',
      category: 'Governance',
      description: 'Ethics or IRB approval record with dates, scope, and renewal status.',
      fields: ['protocolId', 'approvalBody', 'approvedUses', 'effectiveDate', 'expiryDate', 'status']
    },
    {
      id: 'consent-record',
      name: 'ConsentRecordHolon',
      category: 'Governance',
      description: 'Participant consent scope, sharing tier, withdrawal, and permitted uses.',
      fields: ['consentId', 'scope', 'sharingTier', 'recontactAllowed', 'withdrawnAt', 'version']
    },
    {
      id: 'data-access-request',
      name: 'DataAccessRequestHolon',
      category: 'Governance',
      description: 'Request, approval, and expiry for access to a cohort or data subset.',
      fields: ['requestId', 'requester', 'purpose', 'scope', 'decision', 'expiresAt']
    },
    {
      id: 'cohort',
      name: 'CohortHolon',
      category: 'Study Design',
      description: 'Study population with inclusion criteria, exclusions, and governance links.',
      fields: ['cohortId', 'title', 'conditionArea', 'inclusionCriteria', 'exclusionCriteria', 'sizeEstimate'],
      requiredRelationships: ['governed_by', 'has_member']
    },
    {
      id: 'participant',
      name: 'ParticipantHolon',
      category: 'Study Design',
      description: 'De-identified participant record linked to consent, cohort, and observations.',
      fields: ['participantPseudonym', 'cohortId', 'dataAccessTier', 'status'],
      requiredRelationships: ['has_consent', 'member_of']
    },
    {
      id: 'sample',
      name: 'SampleHolon',
      category: 'Biospecimen',
      description: 'Specimen identity, type, collection context, and custody status.',
      fields: ['sampleId', 'sampleType', 'collectionWindow', 'site', 'custodyStatus'],
      requiredRelationships: ['donated_by', 'covered_by_consent']
    },
    {
      id: 'aliquot',
      name: 'AliquotHolon',
      category: 'Biospecimen',
      description: 'Derived unit from a parent sample used by an assay or sequencing run.',
      fields: ['aliquotId', 'parentSampleId', 'volume', 'storageLocation', 'status']
    },
    {
      id: 'sequencing-run',
      name: 'SequencingRunHolon',
      category: 'Lab And Assay',
      description: 'Instrument run, flowcell/lane, status, and produced data handles.',
      fields: ['runId', 'instrument', 'flowcell', 'lane', 'startedAt', 'completedAt', 'status']
    },
    {
      id: 'sequencing-data-object',
      name: 'SequencingDataObjectHolon',
      category: 'Data Asset',
      description: 'Handle to FASTQ, BAM, CRAM, gVCF, or VCF data, with hashes and storage metadata.',
      fields: ['objectId', 'dataType', 'uri', 'checksum', 'sizeBytes', 'referenceGenome', 'accessPolicy']
    },
    {
      id: 'variant-set',
      name: 'VariantSetHolon',
      category: 'Data Asset',
      description: 'Set of called variants generated by a pipeline for a genome or sample.',
      fields: ['variantSetId', 'caller', 'callerVersion', 'referenceGenome', 'qualityThresholds', 'annotationRelease']
    },
    {
      id: 'phenotype-observation',
      name: 'PhenotypeObservationHolon',
      category: 'Phenotype',
      description: 'Phenotype, symptom, biomarker, outcome, or exposure with source and timing.',
      fields: ['observationId', 'ontologyCode', 'label', 'source', 'observedAt', 'confidence']
    },
    {
      id: 'pipeline-run',
      name: 'PipelineRunHolon',
      category: 'Analysis',
      description: 'Workflow or container run with immutable inputs, outputs, parameters, and status.',
      fields: ['runId', 'workflowRef', 'containerDigest', 'parametersHash', 'status', 'startedAt', 'completedAt']
    },
    {
      id: 'agent-action',
      name: 'AgentActionHolon',
      category: 'Analysis',
      description: 'Audited model, tool, or agent step that acted on Holon inputs.',
      fields: ['actionId', 'actor', 'toolName', 'modelVersion', 'inputHolonIds', 'outputHolonIds', 'timestamp']
    },
    {
      id: 'evidence-record',
      name: 'EvidenceRecordHolon',
      category: 'Evidence',
      description: 'Durable evidence output linking inputs, method, result, reviewer, and limitations.',
      fields: ['evidenceId', 'summary', 'inputHolonIds', 'methodRef', 'limitations', 'reviewStatus']
    },
    {
      id: 'claim',
      name: 'ClaimHolon',
      category: 'Evidence',
      description: 'Explicit claim supported by evidence and separated from clinical action.',
      fields: ['claimId', 'claimText', 'intendedUse', 'confidence', 'reviewStatus']
    },
    {
      id: 'sign-off',
      name: 'SignOffHolon',
      category: 'Review',
      description: 'Human review or committee decision with role, decision, and timestamp.',
      fields: ['signOffId', 'reviewerRole', 'decision', 'notes', 'timestamp']
    },
    {
      id: 'method-package',
      name: 'MethodPackageHolon',
      category: 'Publication',
      description: 'Reusable schema, recipe, synthetic dataset, or analysis method intended for sharing.',
      fields: ['packageId', 'title', 'version', 'assets', 'license', 'publishStatus']
    }
  ],
  relationships: [
    {
      id: 'governed_by',
      label: 'governed_by',
      from: 'ResearchProgramHolon',
      to: 'IRBProtocolHolon',
      description: 'Program or cohort is governed by an ethics or protocol record.'
    },
    {
      id: 'has_member',
      label: 'has_member',
      from: 'CohortHolon',
      to: 'ParticipantHolon',
      description: 'Cohort includes a de-identified participant.'
    },
    {
      id: 'member_of',
      label: 'member_of',
      from: 'ParticipantHolon',
      to: 'CohortHolon',
      description: 'Participant is a member of a cohort.'
    },
    {
      id: 'has_consent',
      label: 'has_consent',
      from: 'ParticipantHolon',
      to: 'ConsentRecordHolon',
      description: 'Participant is covered by a consent scope and version.'
    },
    {
      id: 'covered_by_consent',
      label: 'covered_by_consent',
      from: 'SampleHolon',
      to: 'ConsentRecordHolon',
      description: 'Sample use is covered by a consent record.'
    },
    {
      id: 'donated',
      label: 'donated',
      from: 'ParticipantHolon',
      to: 'SampleHolon',
      description: 'Participant donated or is linked to a specimen.'
    },
    {
      id: 'donated_by',
      label: 'donated_by',
      from: 'SampleHolon',
      to: 'ParticipantHolon',
      description: 'Sample was donated by or linked to a participant.'
    },
    {
      id: 'derived_from',
      label: 'derived_from',
      from: 'AliquotHolon',
      to: 'SampleHolon',
      description: 'Aliquot or downstream asset derives from a parent sample.'
    },
    {
      id: 'input_to',
      label: 'input_to',
      from: 'SampleHolon',
      to: 'SequencingRunHolon',
      description: 'Sample or aliquot is an input to an assay or sequencing run.'
    },
    {
      id: 'produced',
      label: 'produced',
      from: 'SequencingRunHolon',
      to: 'SequencingDataObjectHolon',
      description: 'Sequencing run produced data object handles.'
    },
    {
      id: 'called_variants',
      label: 'called_variants',
      from: 'PipelineRunHolon',
      to: 'VariantSetHolon',
      description: 'Pipeline run produced a variant set.'
    },
    {
      id: 'observed',
      label: 'observed',
      from: 'ParticipantHolon',
      to: 'PhenotypeObservationHolon',
      description: 'Participant has a phenotype, outcome, or biomarker observation.'
    },
    {
      id: 'supports',
      label: 'supports',
      from: 'EvidenceRecordHolon',
      to: 'ClaimHolon',
      description: 'Evidence supports an explicit research or decision-support claim.'
    },
    {
      id: 'reviewed_by',
      label: 'reviewed_by',
      from: 'ClaimHolon',
      to: 'SignOffHolon',
      description: 'Claim has a human review or sign-off record.'
    }
  ],
  recipes: [
    {
      id: 'create-synthetic-cohort-graph',
      title: 'Create Synthetic Cohort Graph',
      description: 'Create a small non-PHI cohort graph with consent, participant, sample, genome handle, phenotype, and evidence placeholders.',
      steps: [
        {
          label: 'Plan schema',
          description: 'Review selected Holon types and confirm all data is synthetic or de-identified.',
          mode: 'plan'
        },
        {
          label: 'Create core Holons',
          description: 'Create ResearchProgram, Cohort, ConsentRecord, Participant, Sample, SequencingDataObject, PhenotypeObservation, and EvidenceRecord.',
          mode: 'execute'
        },
        {
          label: 'Link graph',
          description: 'Connect Holons with governed_by, has_member, has_consent, donated, observed, and supports edges.',
          mode: 'execute'
        }
      ]
    },
    {
      id: 'attach-genome-handle',
      title: 'Attach Genome Handle',
      description: 'Attach a storage pointer, checksum, reference genome, and access policy to an existing sample or sequencing run.',
      steps: [
        {
          label: 'Validate access policy',
          description: 'Confirm consent and data-use scope before adding a genome data handle.',
          mode: 'plan'
        },
        {
          label: 'Create data object',
          description: 'Create a SequencingDataObjectHolon with URI, checksum, data type, and reference metadata.',
          mode: 'execute'
        }
      ]
    },
    {
      id: 'record-evidence-summary',
      title: 'Record Evidence Summary',
      description: 'Create a bounded EvidenceRecordHolon from selected inputs, method metadata, limitations, and reviewer state.',
      steps: [
        {
          label: 'Draft evidence',
          description: 'Summarize inputs, method, result, and limitations without making a clinical claim.',
          mode: 'plan'
        },
        {
          label: 'Save evidence',
          description: 'Persist the evidence record and link it to input Holons and any claim or sign-off records.',
          mode: 'execute'
        }
      ]
    }
  ],
  quickActions: [
    {
      id: 'draft-cohort-graph',
      label: 'Draft cohort graph',
      description: 'Ask Composer to plan a synthetic cohort graph using the active Genomic Medicine pack.',
      mode: 'plan',
      prompt:
        'Using the Genomic Medicine domain pack, draft a synthetic cohort Holon graph. Include ResearchProgramHolon, CohortHolon, ConsentRecordHolon, ParticipantHolon, SampleHolon, SequencingDataObjectHolon, PhenotypeObservationHolon, and EvidenceRecordHolon. Keep this in Plan mode and do not create records yet.'
    },
    {
      id: 'prepare-genome-handle',
      label: 'Prepare genome handle',
      description: 'Draft the metadata needed to attach an approved genome data pointer.',
      mode: 'plan',
      prompt:
        'Using the Genomic Medicine domain pack, prepare a SequencingDataObjectHolon draft for an approved or synthetic genome handle. Include data type, URI placeholder, checksum placeholder, reference genome, access policy, and consent checks. Do not include PHI.'
    },
    {
      id: 'draft-evidence-record',
      label: 'Draft evidence record',
      description: 'Draft a bounded evidence summary that avoids clinical overclaiming.',
      mode: 'plan',
      prompt:
        'Using the Genomic Medicine domain pack, draft an EvidenceRecordHolon from selected synthetic inputs. Include input Holon ids as placeholders, method reference, result summary, limitations, review status, and a clear statement that this is research or decision support, not a clinical order.'
    }
  ],
  dashboardTabs: [
    {
      id: 'data-commons',
      label: 'Data Commons',
      description: 'Cohorts, participants, consent links, genome handles, and phenotype observations.',
      holonSchemaIds: ['research-program', 'cohort', 'participant', 'consent-record', 'sequencing-data-object', 'phenotype-observation'],
      recipeIds: ['create-synthetic-cohort-graph']
    },
    {
      id: 'governance',
      label: 'Consent And Governance',
      description: 'Consent, ethics review, data-use agreements, and access requests.',
      holonSchemaIds: ['irb-protocol', 'consent-record', 'data-access-request']
    },
    {
      id: 'lab',
      label: 'Lab And Assays',
      description: 'Samples, aliquots, sequencing runs, instruments, and run provenance.',
      holonSchemaIds: ['sample', 'aliquot', 'sequencing-run', 'sequencing-data-object'],
      recipeIds: ['attach-genome-handle']
    },
    {
      id: 'analysis',
      label: 'Analysis Pipeline',
      description: 'Pipeline runs, model or agent actions, variant sets, and interpretation steps.',
      holonSchemaIds: ['pipeline-run', 'agent-action', 'variant-set']
    },
    {
      id: 'evidence',
      label: 'Evidence Graph',
      description: 'Evidence records, claims, limitations, review steps, and sign-off.',
      holonSchemaIds: ['evidence-record', 'claim', 'sign-off'],
      recipeIds: ['record-evidence-summary']
    },
    {
      id: 'publish',
      label: 'Publish Methods',
      description: 'Reusable schemas, recipes, synthetic datasets, and method packages.',
      holonSchemaIds: ['method-package']
    }
  ],
  safetyRules: [
    {
      id: 'no-phi-prompts',
      title: 'No PHI in prompts',
      description: 'Shared IDE and agent surfaces should use synthetic or de-identified metadata by default.'
    },
    {
      id: 'consent-before-widen',
      title: 'Consent before widening use',
      description: 'Exports, publication, external agents, and new analysis purposes must check consent and data-use scope first.'
    },
    {
      id: 'plan-before-mutation',
      title: 'Plan before mutation',
      description: 'Use Plan mode for discovery and dry-runs; Execute mode is required for creates, updates, exports, and publication.'
    },
    {
      id: 'no-clinical-claim',
      title: 'Separate evidence from clinical action',
      description: 'Evidence and hypotheses must state intended use and review status; they are not silent medical orders.'
    }
  ]
};
