import type { EntitlementSlotCatalogEntry } from './entitlementSlotsTypes.js';

/** Display catalog; keep in sync with docs/NFT_ENTITLEMENT_SLOTS_SPEC.md §6 */
export const ENTITLEMENT_SLOTS_CATALOG: EntitlementSlotCatalogEntry[] = [
  {
    skuId: 'founder-annual',
    category: 'access',
    title: 'Founder Annual',
    shortDescription: 'On-chain pass for Founder Annual IDE access.',
    unlocksSummary: 'Commercial Johnny SKU at GA after redemption (see founder campaign docs).',
    featureFlags: ['ide.access.founder_annual'],
  },
  {
    skuId: 'founder-lifetime-ga',
    category: 'access',
    title: 'Founder Lifetime (GA baseline)',
    shortDescription: 'Grandfathered GA feature set at public launch.',
    unlocksSummary: 'Ongoing right to GA-baseline IDE entitlements; upgrades may be separate SKUs.',
    featureFlags: ['ide.access.founder_lifetime_ga'],
  },
  {
    skuId: 'solana-builder-pass',
    category: 'chain',
    title: 'Solana Builder Pass',
    shortDescription: 'Solana mint workflows and Solana-scoped actions.',
    unlocksSummary: 'oasis_workflow_mint_solana_nft, Solana defaults, Solana wallet flows.',
    featureFlags: ['mcp.mint.solana', 'chain.solana'],
  },
  {
    skuId: 'evm-core-pass',
    category: 'chain',
    title: 'EVM Core Pass',
    shortDescription: 'Tier-A EVM mint workflow chains.',
    unlocksSummary: 'oasis_workflow_mint_nft for Ethereum, Base, Arbitrum, Polygon, Optimism, Avalanche, BNB, Fantom.',
    featureFlags: ['mcp.mint.evm_tier_a'],
  },
  {
    skuId: 'geonft-studio-pass',
    category: 'oasis',
    title: 'GeoNFT Studio',
    shortDescription: 'Place and query geo-anchored NFTs.',
    unlocksSummary: 'oasis_place_geo_nft, oasis_get_geo_nfts*, map-heavy recipes.',
    featureFlags: ['mcp.geonft'],
  },
  {
    skuId: 'starnet-publisher-pass',
    category: 'oasis',
    title: 'STARNET Publisher',
    shortDescription: 'Publish and activate on STARNET.',
    unlocksSummary: 'star_publish_oapp, star_activate_oapp, republish flows where product gates writes.',
    featureFlags: ['starnet.publish'],
  },
  {
    skuId: 'game-content-studio-pass',
    category: 'oasis',
    title: 'Game Content Studio',
    shortDescription: 'Author quests, missions, NPCs, and items.',
    unlocksSummary: 'Mutating star_* for quest, mission, NPC, item holons vs read-only lists.',
    featureFlags: ['star.game_content.write'],
  },
  {
    skuId: 'voice-studio-pass',
    category: 'integration',
    title: 'Voice Studio',
    shortDescription: 'ElevenLabs voice tools via MCP.',
    unlocksSummary: 'elevenlabs_list_voices, tts preview, create_agent, clone_voice (tiered).',
    featureFlags: ['integration.elevenlabs'],
  },
  {
    skuId: 'unity-bridge-pass',
    category: 'integration',
    title: 'Unity Bridge',
    shortDescription: 'Unity Editor MCP bridge.',
    unlocksSummary: 'unity_* MCP tools for scene objects, play mode, components.',
    featureFlags: ['integration.unity_mcp'],
  },
  {
    skuId: 'partner-season-badge',
    category: 'community',
    title: 'Partner / Season badge',
    shortDescription: 'Optional cosmetic or community perks.',
    unlocksSummary: 'Badges, seasonal UI, or bundled quota (product-defined).',
    featureFlags: ['ide.cosmetic.partner_season'],
  },
];
